# Remember change this according to your path
grid_file: "/home/laojk/Code/Gazebo-Testing-Platform/src/move_grid/command/movement.txt"

grid_map:
  max_x: 65
  max_y: 65
  grid_size: 0.15
  trans_kp: 0.03
  trans_ki: 0.0001
  trans_kd: 0.001
  angle_kp: 0.05
  angle_ki: 0.001
  angle_kd: 0.01